### ISSUE TITLE
Negative weights

### ISSUE THREAD

**Issue by emackev** [BasisResearch/cities#116]
The negative weights made the distance equation quite complicated and difficult to parse. I suggest removing them, because they aren't used in the front end. I'm also not confident they're being calculated correctly. In the equation below, the `+2` here makes the range different for the negative weights compared to positive weights (since all values are in [-1, 1]). If we don't remove them, please:

A) in the documentation, first describe the main simple positive weight case, then add the negative weight case as a separate section (so as not to confuse users who won't use the negative weights)

B) double check that the equations are correct

screenshot from similarity_conceptual.ipynb:

![image](https://github.com/BasisResearch/cities/assets/2993689/b519dc5b-3d52-4256-95d9-9ae8e97b86fd)

**Comment by rfl-urbaniak** [comment]
not relevant anymore
