### ISSUE TITLE
Consider refactoring euclidean kin finding (discuss with Andy)

### ISSUE THREAD

**Issue by Niklewa** [BasisResearch/cities#21]
I think if you want to go this route (rather than passing in all the requisite components to compute the weight array), I would just define an abstract base class with this method, and require that inheritors surface the attributes required to perform this computation.

That said, I might consider ways to do this more functionally, as that can be a lot easier to test and keep concerns separate.

_Originally posted by @azane in https://github.com/BasisResearch/cities/pull/14#discussion_r1365940506_

**Comment by rfl-urbaniak** [comment]
not relevant anymore
