### ISSUE TITLE
add error throwing to the rescaling function

### ISSUE THREAD

**Issue by Niklewa** [BasisResearch/cities#23]
IIRC you're limiting the rescaling behavior to float64 right now, maybe some `raise NotImplementedError()` for numerics that you won't be rescaling? Or maybe just showing a warning.

_Originally posted by @azane in https://github.com/BasisResearch/cities/pull/14#discussion_r1364013494_

**Comment by rfl-urbaniak** [comment]
will not work on similarity further.
