### ISSUE TITLE
if further development is the plan, consider moving to pyspark

### ISSUE THREAD

**Issue by Niklewa** [BasisResearch/cities#24]
This is a more general comment, but I'm wondering if a lightweight database system would be better here? E.g. some lightweight [pyspark](https://spark.apache.org/docs/latest/api/python/index.html) (probably overkill...) setup might standardize some of this logic, keep you from needing separate wide/long formats, enable joins etc. that would keep things flexible without having to manage all these dictionaries and keys.

_Originally posted by @azane in https://github.com/BasisResearch/cities/pull/14#discussion_r1364067437_

**Comment by rfl-urbaniak** [comment]
moved to a db
