### ISSUE TITLE
downstream: add metadata extraction & check

### ISSUE THREAD

**Issue by Niklewa** [BasisResearch/cities#25]
I'm wondering if these metadata keys can be pulled out into constants? For easier refactoring, IDE integration, code completion, etc. In general, would be nice to have some enforcement of the metadata convention. Maybe just some util functions that parse the metadata and features from a dataframe.

_Originally posted by @azane in https://github.com/BasisResearch/cities/pull/14#discussion_r1364078889_

**Comment by rfl-urbaniak** [comment]
not relevant anymore
