### ISSUE TITLE
potentially add hierarchical structure to the models

### ISSUE THREAD

**Issue by Niklewa** [BasisResearch/cities#28]
This is a great rundown!

High level thoughts:

1. It would be great to more robustly handle missing data. This might be another reason to consider a fully bayesian approach, as "missing data" simply doesn't show up in conditioning statements.
2. Similarly, would love a generalizeable solution to the multi-level nature of this data. Again a bayesian approach should be able to handle these hierarchical relationships well.

It's not clear to me whether a robust bayesian approach is something to prioritize now, later in the sprint, or after the sprint. My hunch is to stick with what we have and get the tool in front of users ASAP, then circle back.

_Originally posted by @azane in https://github.com/BasisResearch/cities/pull/14#discussion_r1365911928_

**Comment by rfl-urbaniak** [comment]
Not in these models.
