### ISSUE TITLE
importing cities package in other projects fails because data folder isn't copied over

### ISSUE THREAD

**Issue by riadas** [BasisResearch/cities#42]
To get the cities package properly imported into the cities-app repo, I had to manually copy the `data` folder from this repo into cities-app. Everything is working now in cities-app, but not sure if this manual copying is the desired workflow -- wanted to check with you about this @rfl-urbaniak @Niklewa.

**Comment by rfl-urbaniak** [comment]
will not work on. moved to the db pipeline for the new project.
