### ISSUE TITLE
.pkl format for exclusions is difficult to access/interpret

### ISSUE THREAD

**Issue by emackev** [BasisResearch/cities#52]
A .csv would be simpler/more accessible. 

This is the current format of the exclusions.pkl file: 

In [3]: with open("../data/raw/exclusions.pkl", "rb") as file:
   ...:         exclusions = pickle.load(file)
   ...: 

In [4]: exclusions
Out[4]: 
{'transport': array([15901, 51901, 51903, 51907, 51911, 51913, 51918, 51919, 51921,
        51923, 51929, 51931, 51933, 51939, 51941, 51942, 51944, 51945,
        51947, 51949, 51951, 51953, 51955, 51958])}

**Comment by rfl-urbaniak** [comment]
won't do
