### ISSUE TITLE
Data: Fill in the few missing counties' data (manually or scraping)

### ISSUE THREAD

**Issue by riadas** [BasisResearch/cities#66]
For the existing data variables on the frontend (Population, GDP, Industry Composition, Urbanicity, Ethnic Composition). Maybe the three spending variables too, but that seems harder/less necessary.

**Comment by emackev** [comment]
@Niklewa , we learned from the user advocates that the reason lots of counties aren't showing up in the state of Virginia is that there are a lot of independent cities that are treated as counties. Do you remember which dataset(s) excluded the Virginia counties? I think this could be a very simple case of how they are labeled in the dataset (the standard is to treat them as counties, even though technically they are cities).

**Comment by Niklewa** [comment]
@emackev, I have investigated this issue. The raw dataset for both GDP and population contains 81 FIPS codes for Virginia. However, the one used for ethnic composition contains 188 unique FIPS codes. For the context: 

"The Commonwealth of Virginia is divided into 95 counties, along with 38 independent cities that are considered county-equivalents for census purposes."

**Comment by emackev** [comment]
Thanks for checking this!!

**Comment by rfl-urbaniak** [comment]
done
